- name: Ensure EPEL is installed.
  package:
    name: epel-release
    state: present
  when: ansible_os_family == "RedHat" and ansible_distribution != "Fedora" and ansible_distribution_major_version|int < 9

- name: Add yum KIT repository CentOS
  get_url:
    url: https://repo.data.kit.edu/data-kit-edu-centos{{ansible_distribution_major_version}}.repo
    dest: /etc/yum.repos.d/data-kit-edu-centos{{ansible_distribution_major_version}}.repo
  when: ansible_distribution_release != "Stream"

- name: Add yum KIT repository CentOS Stream
  get_url:
    url: https://repo.data.kit.edu/data-kit-edu-centos-stream.repo
    dest: /etc/yum.repos.d/data-kit-edu-centos-stream.repo
  when: ansible_distribution_release == "Stream"

- name: Install pyyaml in CentOS 8
  yum:
    name: https://cbs.centos.org/kojifiles/packages/PyYAML/5.4.1/2.el8/x86_64/python3-pyyaml-5.4.1-2.el8.x86_64.rpm
    disable_gpg_check: yes
  when: ansible_distribution_major_version == "8"

- name: Install centos-release-scl in CentOS 7
  yum:
    name: centos-release-scl
  when: ansible_distribution_major_version == "7"

- name: Install python38 in CentOS 7
  yum:
    name: rh-python38
  when: ansible_distribution_major_version == "7"

- name: Enable python38 pip in CentOS 7
  file:
    src: /opt/rh/rh-python38/root/usr/bin/pip3
    dest: /usr/bin/pip3
    state: link
    force: yes
  when: ansible_distribution_major_version == "7"

- name: Ensure Pip3 is installed
  package:
    name: python3-pip
    state: present
  when: ansible_distribution_major_version != "7"
