- name: Install requisites
  apt:
    install_recommends: false
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - python3
      - python3-pip
      - python3-setuptools

- name: Remove old pkgs
  apt:
    state: absent
    name:
    - python3-yaml
    - python-yaml
  ignore_errors: true

- name: Add apt KIT repository key ubuntu
  apt_key:
    url: https://repo.data.kit.edu/repo-data-kit-edu-key.gpg
    state: present

- name: Add apt KIT repository ubuntu
  apt_repository:
    repo: deb https://repo.data.kit.edu/ubuntu/{{ansible_distribution_version}} ./
    state: present
