- name: Restart sshd
  service:
    name: "{{ 'ssh' if ansible_facts.os_family == 'Debian' else 'sshd' }}"
    state: restarted

- name: Restart motley-cue
  import_tasks: tasks/restart_motley_cue.yaml
